// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamStrategyAndTasks.Infrastructure.Data;

#nullable disable

namespace TeamStrategyAndTasks.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324125916_AddNodeRisks")]
    partial class AddNodeRisks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer")
                        .HasColumnName("node_type");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer")
                        .HasColumnName("node_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_logs_occurred_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("NodeType", "NodeId")
                        .HasDatabaseName("ix_audit_logs_node_type_node_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.BusinessProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuccessMetric")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("success_metric");

                    b.Property<DateTimeOffset?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("TargetValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_value");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_business_processes");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_business_processes_is_archived");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_business_processes_owner_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_business_processes_team_id");

                    b.ToTable("business_processes", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer")
                        .HasColumnName("node_type");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parent_comment_id");

                    b.HasIndex("NodeType", "NodeId")
                        .HasDatabaseName("ix_comments_node_type_node_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_initiatives");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_initiatives_is_archived");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_initiatives_owner_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_initiatives_team_id");

                    b.ToTable("initiatives", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.InitiativeWorkTask", b =>
                {
                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiative_id");

                    b.Property<Guid>("WorkTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_task_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("InitiativeId", "WorkTaskId")
                        .HasName("pk_initiative_work_tasks");

                    b.HasIndex("WorkTaskId")
                        .HasDatabaseName("ix_initiative_work_tasks_work_task_id");

                    b.ToTable("initiative_work_tasks", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.KeyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_value");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("objective_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("TargetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_key_results");

                    b.HasIndex("ObjectiveId")
                        .HasDatabaseName("ix_key_results_objective_id");

                    b.ToTable("key_results", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("InitiativeId", "DueDate")
                        .HasDatabaseName("ix_milestones_initiative_id_due_date");

                    b.HasIndex("Status", "DueDate")
                        .HasDatabaseName("ix_milestones_status_due_date");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.NodeDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<string>("BlockedType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blocked_type");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<string>("BlockerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blocker_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dependency_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_node_dependencies");

                    b.HasIndex("BlockedType", "BlockedId")
                        .HasDatabaseName("ix_node_dependencies_blocked_type_blocked_id");

                    b.HasIndex("BlockerType", "BlockerId")
                        .HasDatabaseName("ix_node_dependencies_blocker_type_blocker_id");

                    b.HasIndex("BlockerType", "BlockerId", "BlockedType", "BlockedId")
                        .IsUnique()
                        .HasDatabaseName("ix_node_dependencies_blocker_type_blocker_id_blocked_type_bloc");

                    b.ToTable("node_dependencies", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.NodeRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("impact");

                    b.Property<string>("MitigationPlan")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mitigation_plan");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("node_type");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("probability");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_node_risks");

                    b.HasIndex("NodeType", "NodeId")
                        .HasDatabaseName("ix_node_risks_node_type_node_id");

                    b.HasIndex("Status", "Probability", "Impact")
                        .HasDatabaseName("ix_node_risks_status_probability_impact");

                    b.ToTable("node_risks", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("RelatedNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_node_id");

                    b.Property<int?>("RelatedNodeType")
                        .HasColumnType("integer")
                        .HasColumnName("related_node_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuccessMetric")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("success_metric");

                    b.Property<DateTimeOffset?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("TargetValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_value");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_objectives");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_objectives_is_archived");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_objectives_owner_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_objectives_team_id");

                    b.ToTable("objectives", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.ObjectiveProcess", b =>
                {
                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("objective_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ObjectiveId", "ProcessId")
                        .HasName("pk_objective_processes");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_objective_processes_process_id");

                    b.ToTable("objective_processes", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.ProcessInitiative", b =>
                {
                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiative_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProcessId", "InitiativeId")
                        .HasName("pk_process_initiatives");

                    b.HasIndex("InitiativeId")
                        .HasDatabaseName("ix_process_initiatives_initiative_id");

                    b.ToTable("process_initiatives", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.SavedFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filter_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("page_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_filters");

                    b.HasIndex("UserId", "PageKey")
                        .HasDatabaseName("ix_saved_filters_user_id_page_key");

                    b.ToTable("saved_filters", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionInitiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_suggestion_initiatives");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_suggestion_initiatives_is_active");

                    b.ToTable("suggestion_initiatives", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionInitiativeTask", b =>
                {
                    b.Property<Guid>("SuggestionInitiativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_initiative_id");

                    b.Property<Guid>("SuggestionTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_task_id");

                    b.HasKey("SuggestionInitiativeId", "SuggestionTaskId")
                        .HasName("pk_suggestion_initiative_tasks");

                    b.HasIndex("SuggestionTaskId")
                        .HasDatabaseName("ix_suggestion_initiative_tasks_suggestion_task_id");

                    b.ToTable("suggestion_initiative_tasks", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_suggestion_objectives");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_suggestion_objectives_is_active");

                    b.ToTable("suggestion_objectives", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionObjectiveProcess", b =>
                {
                    b.Property<Guid>("SuggestionObjectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_objective_id");

                    b.Property<Guid>("SuggestionProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_process_id");

                    b.HasKey("SuggestionObjectiveId", "SuggestionProcessId")
                        .HasName("pk_suggestion_objective_processes");

                    b.HasIndex("SuggestionProcessId")
                        .HasDatabaseName("ix_suggestion_objective_processes_suggestion_process_id");

                    b.ToTable("suggestion_objective_processes", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_suggestion_processes");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_suggestion_processes_is_active");

                    b.ToTable("suggestion_processes", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionProcessInitiative", b =>
                {
                    b.Property<Guid>("SuggestionProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_process_id");

                    b.Property<Guid>("SuggestionInitiativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_initiative_id");

                    b.HasKey("SuggestionProcessId", "SuggestionInitiativeId")
                        .HasName("pk_suggestion_process_initiatives");

                    b.HasIndex("SuggestionInitiativeId")
                        .HasDatabaseName("ix_suggestion_process_initiatives_suggestion_initiative_id");

                    b.ToTable("suggestion_process_initiatives", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_suggestion_tasks");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_suggestion_tasks_is_active");

                    b.ToTable("suggestion_tasks", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Mandate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mandate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_teams_is_archived");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("TeamId", "UserId")
                        .HasName("pk_team_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_members_user_id");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("EventFilter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("*")
                        .HasColumnName("event_filter");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Secret")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("secret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_webhook_subscriptions");

                    b.ToTable("webhook_subscriptions", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActualEffort")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("actual_effort");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset?>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedEffort")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_effort");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_tasks");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_work_tasks_assignee_id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_work_tasks_is_archived");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_work_tasks_owner_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_work_tasks_team_id");

                    b.ToTable("work_tasks", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.BusinessProcess", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_business_processes_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Comment", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_parent_comment_id");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Initiative", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_initiatives_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.InitiativeWorkTask", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Initiative", "Initiative")
                        .WithMany("InitiativeWorkTasks")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_initiative_work_tasks_initiatives_initiative_id");

                    b.HasOne("TeamStrategyAndTasks.Core.Entities.WorkTask", "WorkTask")
                        .WithMany("InitiativeWorkTasks")
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_initiative_work_tasks_work_tasks_work_task_id");

                    b.Navigation("Initiative");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.KeyResult", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Objective", "Objective")
                        .WithMany("KeyResults")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_key_results_objectives_objective_id");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Milestone", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Initiative", "Initiative")
                        .WithMany("Milestones")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_initiatives_initiative_id");

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Objective", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_objectives_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.ObjectiveProcess", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Objective", "Objective")
                        .WithMany("ObjectiveProcesses")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_objective_processes_objectives_objective_id");

                    b.HasOne("TeamStrategyAndTasks.Core.Entities.BusinessProcess", "Process")
                        .WithMany("ObjectiveProcesses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_objective_processes_business_processes_process_id");

                    b.Navigation("Objective");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.ProcessInitiative", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Initiative", "Initiative")
                        .WithMany("ProcessInitiatives")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_initiatives_initiatives_initiative_id");

                    b.HasOne("TeamStrategyAndTasks.Core.Entities.BusinessProcess", "Process")
                        .WithMany("ProcessInitiatives")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_initiatives_business_processes_process_id");

                    b.Navigation("Initiative");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionInitiativeTask", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionInitiative", "SuggestionInitiative")
                        .WithMany("InitiativeTasks")
                        .HasForeignKey("SuggestionInitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_initiative_tasks_suggestion_initiatives_suggesti");

                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionTask", "SuggestionTask")
                        .WithMany("InitiativeTasks")
                        .HasForeignKey("SuggestionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_initiative_tasks_suggestion_tasks_suggestion_tas");

                    b.Navigation("SuggestionInitiative");

                    b.Navigation("SuggestionTask");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionObjectiveProcess", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionObjective", "SuggestionObjective")
                        .WithMany("ObjectiveProcesses")
                        .HasForeignKey("SuggestionObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_objective_processes_suggestion_objectives_sugges");

                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionProcess", "SuggestionProcess")
                        .WithMany("ObjectiveProcesses")
                        .HasForeignKey("SuggestionProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_objective_processes_suggestion_processes_suggest");

                    b.Navigation("SuggestionObjective");

                    b.Navigation("SuggestionProcess");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionProcessInitiative", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionInitiative", "SuggestionInitiative")
                        .WithMany("ProcessInitiatives")
                        .HasForeignKey("SuggestionInitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_process_initiatives_suggestion_initiatives_sugge");

                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionProcess", "SuggestionProcess")
                        .WithMany("ProcessInitiatives")
                        .HasForeignKey("SuggestionProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_process_initiatives_suggestion_processes_suggest");

                    b.Navigation("SuggestionInitiative");

                    b.Navigation("SuggestionProcess");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.TeamMember", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.WorkTask", b =>
                {
                    b.HasOne("TeamStrategyAndTasks.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_tasks_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.BusinessProcess", b =>
                {
                    b.Navigation("ObjectiveProcesses");

                    b.Navigation("ProcessInitiatives");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Initiative", b =>
                {
                    b.Navigation("InitiativeWorkTasks");

                    b.Navigation("Milestones");

                    b.Navigation("ProcessInitiatives");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Objective", b =>
                {
                    b.Navigation("KeyResults");

                    b.Navigation("ObjectiveProcesses");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionInitiative", b =>
                {
                    b.Navigation("InitiativeTasks");

                    b.Navigation("ProcessInitiatives");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionObjective", b =>
                {
                    b.Navigation("ObjectiveProcesses");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionProcess", b =>
                {
                    b.Navigation("ObjectiveProcesses");

                    b.Navigation("ProcessInitiatives");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Suggestions.SuggestionTask", b =>
                {
                    b.Navigation("InitiativeTasks");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.Team", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("TeamStrategyAndTasks.Core.Entities.WorkTask", b =>
                {
                    b.Navigation("InitiativeWorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
